#!/usr/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

echo $PWD
pushd ..
echo Migrating...
bin/console doc:mig:mig
sudo -u www bin/console c:c
