#!/bin/bash
#
# vim:ft=sh

############### Variables ###############

############### Functions ###############

############### Main Part ###############
yes | bin/console doc:mig:mig
sudo -u www-data bin/console c:c
