index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      path: '/dashboard'
      version: 'current'
      permanent: true
      keepQueryParams: true
      keepRequestMethod: true
